version: '3.7'

services:

  sample-prod:
    container_name: sample-prod
    image: sample-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - '1337:80'
    # environment:
      # - VAR=value
